// const swaggerAutogen = require("swagger-autogen")();
// const doc = {
//   info: {
//     title: "My API",
//     description: "Description",
//   },
//   host: "localhost:5000",
// };

// const outputFile = "./swagger-output.json";
// const routes = ["./routes/product.js"];

// /* NOTE: If you are using the express Router, you must pass in the 'routes' only the
// root file where the route starts, such as index.js, app.js, routes.js, etc ... */
// const endpointsFiles = [
//   "./routes/product.js",
//   "./routes/auth.js",
//   "./routes/productCategory.js",
//   "./routes/user.js",
// ];

// swaggerAutogen(outputFile, endpointsFiles);

// // swaggerAutogen(outputFile, routes, doc).then(() => {
// //   require("../server"); // Your project's root file
// // });

const swaggerAutogen = require("swagger-autogen")();

const doc = {
  info: {
    version: "1.0.0",
    title: "My API",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: "localhost:5000",
  basePath: "/",
  schemes: ["http", "https"],
  consumes: ["application/json"],
  produces: ["application/json"],
  tags: [
    {
      name: "User",
      description: "Endpoints",
    },
    {
      name: "products",
      description: "Endpoints",
    },
  ],
  securityDefinitions: {
    apiKeyAuth: {
      type: "apiKey",
      in: "header", // can be "header", "query" or "cookie"
      name: "X-API-KEY", // name of the header, query parameter or cookie
      description: "any description...",
    },
  },
  definitions: {
    Parents: {
      father: "Simon Doe",
      mother: "Marie Doe",
    },
    User: {
      name: "Jhon Doe",
      age: 29,
      parents: {
        $ref: "#/definitions/Parents",
      },
      diplomas: [
        {
          school: "XYZ University",
          year: 2020,
          completed: true,
          internship: {
            hours: 290,
            location: "XYZ Company",
          },
        },
      ],
    },
    AddUser: {
      $name: "Jhon Doe",
      $age: 29,
      about: "",
    },
  },
};

const outputFile = "./swagger-output.json";
const endpointsFiles = [
  "../routes/auth.js",
  "../routes/product.js",
  "../routes/productCategory.js",
  "../routes/user.js",
];

swaggerAutogen(outputFile, endpointsFiles, doc);
